name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish 
      run: dotnet publish -c Release --no-build -o ./rel
    - name: Put on gh-pages 🚀
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        publish_dir: 'rel/wwwroot' 
        personal_token: ${{ secrets.ACCESS_TOKEN }}
